### ISSUE TITLE
finue-tuning problem

### ISSUE THREAD

**Issue by peternara** [vtddggg/Robust-Vision-Transformer#1]
Hi~ @vtddggg 

I'm trying, but if I set it to https://github.com/vtddggg/Robust-Vision-Transformer/blob/main/robust_models.py#L317, then In https://github.com/vtddggg/Robust-Vision-Transformer/blob/main/robust_models.py#L283 > the length of self.pools is zero.

Why pit model name? > weights/pit_s_809.pth? rvt_small.pth ??
Is this correct?? Looks like a problem...

What are the correct settings to run this exact model?

thanks

**Comment by vtddggg** [comment]
1. Sorry, some codes of down/up sampling are borrowed from [pit](https://github.com/naver-ai/pit). We have not cleaned the code yet 😂. I'll fix it later. 

2. Yes, for `rvt_small` in this implementation, we only use one stage:
```
model = PoolingTransformer(
        image_size=224,
        patch_size=16,
        stride=16,
        base_dims=[64],
        depth=[12],
        heads=[6],
        mlp_ratio=4,
        **kwargs
    )
```
It means there is no pooling layer and the length of `self.pools` being zero is normal. 

We can also train the `rvt_small` with two stages: `[10, 2]`:
```
model = PoolingTransformer(
        image_size=224,
        patch_size=16,
        stride=16,
        base_dims=[64, 64],
        depth=[10, 2],
        heads=[6, 12],
        mlp_ratio=4,
        **kwargs
    )
```
In our experiment, these two cases have no big difference on the performance.

**Comment by peternara** [comment]
Thanks for the quick answer.

Oh, then,
https://github.com/vtddggg/Robust-Vision-Transformer/blob/main/robust_models.py#L283 I think it's normal to just pass it here.
so,
https://github.com/vtddggg/Robust-Vision-Transformer/blob/main/robust_models.py#L286 The above part (#L283) will be skipped, and this part (#L286) will be understood to be in progress.

thanks

**Comment by vtddggg** [comment]
In https://github.com/vtddggg/Robust-Vision-Transformer/commit/81b545aa4ca28826241d582bbef943961848b0a2 commit, I have cleaned the model definition. Finetuning on pretrained model is supported now by adding `--pretrained` argument.  

Let me know if you have any other questions. Thanks
