### ISSUE TITLE
 Where is the Position-Aware Attention Scaling?

### ISSUE THREAD

**Issue by sebastianbreguel** [vtddggg/Robust-Vision-Transformer#10]
I was looking for the implementation of PAAS 
<img width="528" alt="Screenshot 2023-04-28 at 18 11 04" src="https://user-images.githubusercontent.com/62109266/235199303-3ee25593-1bbc-402b-925d-c64eab61a970.png">
I did not find where the module is in the code? Could you help me to figure out the specific location of this module?

Kind regards!

**Comment by vtddggg** [comment]
Please refer to https://github.com/vtddggg/Robust-Vision-Transformer/issues/3
