### ISSUE TITLE
where the code of patch augmentation?

### ISSUE THREAD

**Issue by 1104662797** [vtddggg/Robust-Vision-Transformer#3]
i'm new to Vision Transformer, I can't find your code about patch augmentation, could you give me  tips?  And I want to know the Wp  how to learn position relationship,Like B in ViT?

**Comment by vtddggg** [comment]
1. [here](https://github.com/vtddggg/Robust-Vision-Transformer/blob/78066d0f44542d7d39fde101e14c8c7c01a7630e/engine.py#L59) is the code of patch augmentation.
2. W_{p} is a learnable parameters, which is optimized end-to-end with the whole model.
