### ISSUE TITLE
Where is the Patch-Wise Augmentation module in the code?

### ISSUE THREAD

**Issue by AllenWu18** [vtddggg/Robust-Vision-Transformer#9]
Hi, I am interested in the RVT and I wanna know how the Patch-Wise Augmentation module mentioned in the paper works. But for I am new to Vision Transformer, I did not find where the module is in the code? Could you help me to figure out the specific location of this module?
Many THX! :)

**Comment by vtddggg** [comment]
Please refer to [this](https://github.com/vtddggg/Robust-Vision-Transformer/issues/3) issue
